export const HEALTH_CHECKER_INJECTION_TOKEN = 'OPENMFP_HEALTH_CHECKER';
export const ENV_VARIABLES_PROVIDER_INJECTION_TOKEN = 'OPENMFP_ENV_VARIABLES_PROVIDER';
export const LOGOUT_CALLBACK_INJECTION_TOKEN = 'OPENMFP_LOGOUT_CALLBACK';
