export const HEALTH_CHECKER_INJECTION_TOKEN = 'OPENMFP_HEALTH_CHECKER';
export const ENV_VARIABLES_PROVIDER_INJECTION_TOKEN =
  'OPENMFP_ENV_VARIABLES_PROVIDER';
export const LOGOUT_CALLBACK_INJECTION_TOKEN = 'OPENMFP_LOGOUT_CALLBACK';
export const PORTAL_CONTEXT_INJECTION_TOKEN = 'OPENMFP_PORTAL_CONTEXT';
export const ENTITY_CONTEXT_INJECTION_TOKEN = 'OPENMFP_ENTITY_CONTEXT';
export const FEATURE_TOGGLES_INJECTION_TOKEN = 'OPENMFP_FEATURE_TOGGLES';
export const SERVICE_PROVIDER_INJECTION_TOKEN = 'OPENMFP_SERVICE_PROVIDER';
export const LUIGI_DATA_SERVICE_INJECTION_TOKEN = 'OPENMFP_LUIGI_DATA_SERVICE';
export const AUTH_CALLBACK_INJECTION_TOKEN = 'OPENMFP_AUTH_CALLBACK';
