export const HEALTH_CHECKER_INJECTION_TOKEN = 'HEALTH_CHECKER';
export const ENV_VARIABLES_PROVIDER_INJECTION_TOKEN = 'ENV_VARIABLES_PROVIDER';
export const TENANT_PROVIDER_INJECTION_TOKEN = 'TENANT_PROVIDER';
export const FRAME_CONTEXT_INJECTION_TOKEN = 'FRAME_CONTEXT';
export const ENTITY_CONTEXT_INJECTION_TOKEN = 'ENTITY_CONTEXT';
export const FEATURE_TOGGLES_INJECTION_TOKEN = 'FEATURE_TOGGLES';
export const SERVICE_PROVIDER_INJECTION_TOKEN = 'SERVICE_PROVIDER';
