name: ci
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: false
    uses: openmfp/gha/.github/workflows/pipeline-node-module.yml@main
    secrets: inherit
  publish:
    permissions:
      contents: read
      # id-token: write is required for the automatic generation of provenance statements and trusted publisher releasing
      id-token: write
    runs-on: ubuntu-latest
    # The GitHub Actions Environment configured for the trusted publisher
    environment: npmjs:@openmfp/portal-server-lib
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - name: Publish package
        run: npm publish --provenance --access public
