name: ci
on:
  [push]

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: false
    uses: openmfp/gha/.github/workflows/pipeline-node-module.yml@check_realase
    secrets: inherit
    with:
      mainBranchRef: 'refs/heads/feat/migrate-config-controller'
